version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    ports:
      - 6379:6379

  # API
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    expose:
      - 8080
    links:
      - redis
      - spreader0
      - spreader1

  # Client
  client_0:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - 4242:4242
    links:
      - api
    stdin_open: true
    tty: true

  # Client
  client_1:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - 4242:4242
    links:
      - api
    stdin_open: true
    tty: true

  # Client
  client_2:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - 4242:4242
    links:
      - api
    stdin_open: true
    tty: true

  # Spreader 0
  spreader0:
    build:
      context: .
      dockerfile: docker/spreader/Dockerfile
    entrypoint: ["bin/bc_spreader", "-c", "bin/config_spreader_0.json"]
    expose:
      - 5000
    links:
      - redis

  # Spreader 1
  spreader1:
    build:
      context: .
      dockerfile: docker/spreader/Dockerfile
    entrypoint: ["bin/bc_spreader", "-c", "bin/config_spreader_1.json"]
    expose:
      - 5000
    links:
      - redis
