version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    network_mode: host

  # API
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    network_mode: host

  # Spreader 0
  spreader0:
    build:
      context: .
      dockerfile: docker/spreader/Dockerfile
    entrypoint: ["bin/bc_spreader", "-c", "bin/config_spreader_0.json"]
    network_mode: host

  # Spreader 1
  spreader1:
    build:
      context: .
      dockerfile: docker/spreader/Dockerfile
    entrypoint: ["bin/bc_spreader", "-c", "bin/config_spreader_1.json"]
    network_mode: host
