// Code generated by protoc-gen-go.
// source: room.proto
// DO NOT EDIT!

package dto

import proto "github.com/golang/protobuf/proto"

// discarding unused import google_protobuf "google/protobuf"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Room struct {
	Id *ID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}

func (m *Room) GetId() *ID {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
}
